namespace Franthropy.Dalamud.Automation.Retainers;

public sealed record TalkEventPacketTransportObservation(
    TalkEventPacketTransportState State,
    uint Opcode,
    bool BuilderPacketSuppressed,
    bool ConstructedPacket,
    int PacketsObservedWhileArmed,
    int SizeEligiblePacketsObserved,
    string Message,
    bool InboundEventPlayObserved = false,
    ulong InboundEventObjectId = 0,
    uint InboundEventId = 0,
    short InboundScene = 0,
    ulong InboundSceneFlags = 0,
    byte InboundSceneDataCount = 0,
    uint[]? InboundSceneData = null,
    int InboundEventPlayCount = 0,
    InboundEventPlaySample[]? InboundEventPlaySamples = null,
    bool MatchingInboundEventYieldObserved = false,
    int InboundEventYieldCount = 0,
    InboundEventYieldSample[]? InboundEventYieldSamples = null,
    int InboundActorControlCount = 0,
    InboundActorControlSample[]? InboundActorControlSamples = null,
    int InboundRawPacketCount = 0,
    InboundRawPacketSample[]? InboundRawPacketSamples = null,
    int InboundEventTerminationCount = 0,
    InboundEventTerminationSample[]? InboundEventTerminationSamples = null,
    bool FlightRecorderArmed = false,
    bool FlightRecorderStopped = false,
    int FlightRecorderPacketCount = 0,
    int FlightRecorderOutboundPacketCount = 0,
    int FlightRecorderInboundPacketCount = 0,
    ZonePacketFlightRecorderSample[]? FlightRecorderSamples = null,
    bool LifecycleRecorderArmed = false,
    bool LifecycleRecorderStopped = false,
    int LifecycleOutboundObservedCount = 0,
    int LifecycleInboundObservedCount = 0,
    int LifecycleOutboundDroppedCount = 0,
    int LifecycleInboundDroppedCount = 0,
    ZonePacketFlightRecorderSample[]? LifecycleOutboundSamples = null,
    ZonePacketFlightRecorderSample[]? LifecycleInboundSamples = null,
    PositionFrameShadowObservation? PositionFrameShadow = null,
    int PreludeObservedCount = 0,
    int PreludeDroppedCount = 0,
    ZonePacketPreludeSample[]? PreludeSamples = null)
{
    public bool Pending => State == TalkEventPacketTransportState.AwaitingBuilderPacket;
    public bool Sent => State == TalkEventPacketTransportState.StockPacketSent;
}
