namespace Franthropy.Dalamud.Automation.Retainers;

public sealed record WarmSessionRetentionProbeObservation(
    WarmSessionRetentionProbeState State,
    ulong ActorId,
    uint EventId,
    uint Opcode,
    ushort SelectionSceneId,
    ulong RetainerId,
    bool SelectionCaptured,
    bool TeardownSuppressed,
    bool ReplaySent,
    bool MatchingScene2Observed,
    bool TeardownReleaseSent,
    bool CleanupAcknowledged,
    string? SelectionPacketHex,
    string? TeardownPacketHex,
    int InboundEventPlayCount,
    InboundEventPlaySample[]? InboundEventPlaySamples,
    int InboundEventYieldCount,
    InboundEventYieldSample[]? InboundEventYieldSamples,
    int InboundActorControlCount,
    InboundActorControlSample[]? InboundActorControlSamples,
    int InboundRawPacketCount,
    InboundRawPacketSample[]? InboundRawPacketSamples,
    int PostReplayContinuationCount,
    OutboundYieldEventSceneSample[]? PostReplayContinuationSamples,
    string Message)
{
    public static WarmSessionRetentionProbeObservation Idle { get; } = new(
        WarmSessionRetentionProbeState.Idle,
        0,
        0,
        0,
        0,
        0,
        false,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        0,
        null,
        0,
        null,
        0,
        null,
        0,
        null,
        0,
        null,
        "The warm-session retention observer is idle.");
}
