namespace Franthropy.Dalamud.Automation.Retainers;

public sealed record YieldEventSceneProbeObservation(
    YieldEventSceneProbeState State,
    YieldEventSceneProbeMode Mode,
    ulong ActorId,
    uint EventId,
    uint Opcode,
    ushort SceneId,
    byte YieldId,
    uint Result0,
    uint Result1,
    bool Sent,
    bool ReplacedOriginal,
    bool MatchingEventPlayObserved,
    bool CachedTemplateAvailable,
    ulong RetainerId,
    ulong InboundEventObjectId,
    short InboundScene,
    ulong InboundSceneFlags,
    int InboundEventPlayCount,
    InboundEventPlaySample[]? InboundEventPlaySamples,
    int InboundEventYieldCount,
    InboundEventYieldSample[]? InboundEventYieldSamples,
    int InboundActorControlCount,
    InboundActorControlSample[]? InboundActorControlSamples,
    uint[]? InboundSceneData,
    string? OutboundPacketHex,
    string Message,
    int InboundRawPacketCount = 0,
    InboundRawPacketSample[]? InboundRawPacketSamples = null)
{
    public static YieldEventSceneProbeObservation Idle { get; } = new(
        YieldEventSceneProbeState.Idle,
        YieldEventSceneProbeMode.None,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        false,
        false,
        false,
        false,
        0,
        0,
        0,
        0,
        0,
        null,
        0,
        null,
        0,
        null,
        null,
        null,
        "The yield-event packet observer is idle.");
}
